name: Deploy

on:
  push:
    branches:
      - main  # Tùy thuộc vào tên của branch bạn đang sử dụng

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Chọn phiên bản Python bạn đang sử dụng

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Flask Application
      run: |
        python app.py
